In [4]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv("D:\\sourabh project\\olist-churn-prediction\\data\\raw\\data.csv")

In [6]:
df.head()

,customer_unique_id,recency,frequency,monetary,avg_delay,churn_status
0,0000f46a3911fa3c0805444483337064,293,1,86.22,-2.0,1
1,0000f6ccb0745a6a4b88665a16c9f078,77,1,43.62,-12.0,0
2,0004aac84e0df4da2b147fca70cf8255,44,1,196.89,-8.0,0
3,0005e1862207bf6ccc02e4228effd9a0,299,1,150.12,-28.0,1
4,0006fdc98a402fceb4eb0ee528f6a8d4,163,1,29.00,-12.0,1

In [4]:
df.shape

(39963, 6)

In [5]:
df.describe()

            recency     frequency      monetary     avg_delay  churn_status
count  39963.000000  39963.000000  39963.000000  39963.000000  39963.000000
mean     143.026174      1.030854    164.086914    -12.915016      0.631784
std       95.950508      0.194705    234.428985      9.377200      0.482326
min        0.000000      1.000000     10.070000   -140.000000      0.000000
25%       56.000000      1.000000     62.465000    -17.000000      0.000000
50%      130.000000      1.000000    105.380000    -13.000000      1.000000
75%      217.000000      1.000000    179.280000     -9.000000      1.000000
max      451.000000      8.000000  13664.080000    181.000000      1.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39963 entries, 0 to 39962
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_unique_id  39963 non-null  object
 1   recency             39963 non-null  int64
 2   frequency           39963 non-null  int64
 3   monetary            39963 non-null  float64
 4   avg_delay           39963 non-null  float64
 5   churn_status        39963 non-null  int64
dtypes: float64(2), int64(3), object(1)
memory usage: 1.8+ MB

In [8]:
df.columns

Index(['customer_unique_id', 'recency', 'frequency', 'monetary', 'avg_delay',
       'churn_status'],
      dtype='object')